### ISSUE TITLE
How to: Deployment

### ISSUE THREAD

**Issue by genodeftest** [exaile/moodbar#1]
This is not an issue, but a question:

Do you want to get this code deployed downstream? If yes, then I'd like to contact some downstream maintainers of the moodbar package and ask them to include this new version instead of the GStreamer 0.10-based version.

- [x] [Fedora](https://apps.fedoraproject.org/packages/moodbar)
- [x] [Debian](https://packages.debian.org/source/jessie/moodbar) (only in oldstable, but maybe the maintainer wants to include it into testing)
- [x] [Launchpad](https://launchpad.net/ubuntu/+source/moodbar)
- [x] [Release-Monitoring upstream tracker](https://release-monitoring.org/)

**Comment by sjohannes** [comment]
I want to figure out issues #2 and #3 first before making a proper release. So probably hold on for now.

**Comment by sjohannes** [comment]
I'm pretty happy with the state of the code, I've been testing it and it works really well, so I've released v1.0. If you're still up for contacting potential package maintainers that would be awesome.

**Comment by genodeftest** [comment]
Launchpad: https://bugs.launchpad.net/ubuntu/+source/moodbar/+bug/1753291
Release monitoring upstream tracker: https://release-monitoring.org/project/16966/
Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1551316
Arch: https://aur.archlinux.org/pkgbase/moodbar/flag-comment/ and https://aur.archlinux.org/packages/moodbar/#news

**Comment by genodeftest** [comment]
Debian: via email.
