### ISSUE TITLE
Wood & O'Keefe pdf link is dead

### ISSUE THREAD

**Issue by hackerb9** [exaile/moodbar#10]
Instead of linking to Amarok's 404 page, try the PDF here:
    https://scholar.google.com/scholar?oi=bibs&cluster=1548353732052211254&btnI=1&hl=en

**Comment by genodeftest** [comment]
Hm, that link is dead for me too.

**Comment by sjohannes** [comment]
Thanks for letting us know. It now links to the paper from the official conference website.
