### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by hackerb9** [exaile/moodbar#11]
Meson gives oblique error messages when compiling, for example:

> Meson encountered an error in file meson.build, line 14, column 0:
> Native dependency 'gstreamer-audio-1.0' not found

For Debian and Ubuntu, there is no "gstreamer-audio-1.0", so it is hard to guess what Meson wants. (It turns out to be `gstreamer-plugins-base1.0-dev`). Perhaps it would be good to mention this error message and more explicitly state that the _development_ version of the plugins are needed for building in the README.md. 

It also wouldn't be bad if the prerequisites section included an example. I believe you only need this one line to install all prerequisites on Debian and Ubuntu:

    apt install gstreamer-plugins-base1.0-dev fftw3-dev meson pkgconf

**Comment by genodeftest** [comment]
Hm, the [Readme#Requirements](https://github.com/exaile/moodbar#requirements) section is listing these dependencies already.

**Comment by sjohannes** [comment]
I've added a mention of the error to the readme so hopefully it's clearer.

I'm pretty hesitant about mentioning package names because they differ between distributors.

**Comment by hackerb9** [comment]
Thanks!
