### ISSUE TITLE
OSX Runtime error: Mutex lock failed

### ISSUE THREAD

**Issue by vonqo** [exaile/moodbar#12]
On OSX during runtime, error shows: 
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

So I've traced the error and found the code:
in ```gstfastspecrum.cpp``` at line 139:
```c++
GstFastSpectrumClass* klass = reinterpret_cast<GstFastSpectrumClass*>(
      G_OBJECT_GET_CLASS(spectrum));
  {
    // Debug: mutex lock failed - trace
    std::lock_guard<decltype(klass->fftw_lock)> l(klass->fftw_lock);  // <= This line!

    spectrum->plan = fftw_plan_dft_r2c_1d(
        nfft,
        spectrum->fft_input,
        spectrum->fft_output,
        FFTW_ESTIMATE);
  }
```
After i removed this line: ```std::lock_guard<decltype(klass->fftw_lock)> l(klass->fftw_lock);```, moodbar successfully produced the data in output file.

**Comment by sjohannes** [comment]
I think the error means that `fftw_lock` is used after deleted. Could you try the [global-fftw-mutex](https://github.com/exaile/moodbar/compare/global-fftw-mutex) branch to see if it fixes the issue?

**Comment by vonqo** [comment]
it is fixed

**Comment by sjohannes** [comment]
Do you mean it now works after applying my change, or because of something else? (I haven't merged the branch so I'm a bit confused.)

**Comment by lupino22** [comment]
It is working after applying [global-fftw-mutex](https://github.com/exaile/moodbar/compare/global-fftw-mutex). I think there is no problem for merging the branch. Thanks :D

**Comment by vonqo** [comment]
It is working fine after applying your changes. I think there is no problem for merging the branch. I accidentally reopened the issue haha. Thanks :D

**Comment by sjohannes** [comment]
Thanks; I've merged the changes in now.
