### ISSUE TITLE
Meson encountered an error : Unknown method "set_quoted" in object.

### ISSUE THREAD

**Issue by globeone** [exaile/moodbar#4]
When trying to build this code
on
Ubuntu 16.04.2

 I get the following error:
user@hostname:~/programs/moodbar$ meson --buildtype=release build/
The Meson build system
Version: 0.29.0
Source dir: /home/user/programs/moodbar
Build dir: /home/user/programs/moodbar/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: moodbar
Native cpp compiler: c++ (gcc 5.4.0-6ubuntu1)

**Meson encountered an error in file meson.build, line 8, column 5:**
Unknown method "set_quoted" in object.

**Comment by genodeftest** [comment]
I cannot reproduce your issue. In case you were using the git repository before, did you make sure to `git clean` it prior to invoking meson?

Your issue may also be caused by the very old versions of Meson or GCC or dependencies you are using. My output looks pretty different:
```
$ meson --buildtype=release build/
The Meson build system
Version: 0.45.1
Source dir: /home/username/src/EXAILE/moodbar
Build dir: /home/username/src/EXAILE/moodbar/build
Build type: native build
Project name: moodbar
Native C++ compiler: ccache c++ (gcc 7.3.1 "c++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring moodbar-config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.3.12)
Native dependency gstreamer-1.0 found: YES 1.12.4
Native dependency gstreamer-audio-1.0 found: YES 1.12.4
Native dependency fftw3 found: YES 3.3.5
Native dependency glib-2.0 found: YES 2.54.3
Native dependency gio-2.0 found: YES 2.54.3
Program test.py found: YES (/home/username/src/EXAILE/moodbar/test.py)
Build targets in project: 3
Found ninja-1.8.2 at /usr/bin/ninja
```
PS: You may want to put your code into a code block, see the link [Styling with Markdown is supported](https://guides.github.com/features/mastering-markdown/) below the comment field.

**Comment by genodeftest** [comment]
Having a look at the config file it looks like this is an issue with your meson version. The method `set_quoted` has been introduced with meson 0.35 [about 1.5 years ago](https://github.com/mesonbuild/meson/commit/09fdc7f815d8b6dede94a14a15a0c05fd1a621c1). Updating to a version newer than 0.35 should solve this problem.

**Comment by sjohannes** [comment]
Yeah, this happens on old Meson versions. If updating Meson is not convenient, you can apply this patch instead:

```diff
diff --git a/meson.build b/meson.build
index a4d68e5..9b6b180 100644
--- a/meson.build
+++ b/meson.build
@@ -4,10 +4,6 @@ project('moodbar', 'cpp',
   default_options : 'cpp_std=c++14',
 )
 
-conf = configuration_data()
-conf.set_quoted('MOODBAR_VERSION_STR', meson.project_version())
-configure_file(output : 'moodbar-config.h', configuration : conf)
-
 dep_gstreamer = dependency('gstreamer-1.0')
 
 gstfastspectrum = static_library('gstfastspectrum',
diff --git a/moodbar_exe.cpp b/moodbar_exe.cpp
index 71a90d7..ee67c2c 100644
--- a/moodbar_exe.cpp
+++ b/moodbar_exe.cpp
@@ -16,7 +16,7 @@
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
 
-#include "moodbar-config.h"
+#define MOODBAR_VERSION_STR "1.0"
 #include "moodbar.h"
 
 #include <gio/gio.h>
```

**Comment by globeone** [comment]
`sudo apt install -t xenial-backports meson`
got met the 0.40.1 version of meson

Now I get
```
user@hostname:~/programs/moodbar$ meson --buildtype=release build/
The Meson build system
Version: 0.40.1
Source dir: /home/user/programs/moodbar
Build dir: /home/user/programs/moodbar/build
Build type: native build
Project name: moodbar
Native cpp compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring moodbar-config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
```

**Meson encountered an error in file meson.build, line 11, column 0:**
Native dependency **'gstreamer-1.0'** not found

Yet:
dpkg -l |grep gstreamer1
 shows:

```
ii  gstreamer1.0-alsa:amd64                         1.8.3-1ubuntu0.2   amd64    GStreamer plugin for ALSA
ii  gstreamer1.0-clutter-3.0                        3.0.18-1           amd64    Clutter PLugin for GStreamer 1.0
ii  gstreamer1.0-fluendo-mp3:amd64                  0.10.32.debian-1   amd64    Fluendo mp3 decoder GStreamer 1.0 plugin
ii  gstreamer1.0-libav:amd64            	    1.8.3-1ubuntu0.2   amd64    libav plugin for GStreamer
ii  gstreamer1.0-plugins-bad:amd64      	    1.8.3-1ubuntu0.2   amd64    GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64             1.8.3-1ubuntu0.2   amd64    GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64     1.8.3-1ubuntu0.2   amd64    GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-base:amd64                 1.8.3-1ubuntu0.2   amd64    GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base-apps    		    1.8.3-1ubuntu0.2   amd64    GStreamer helper programs from the "base" set
ii  gstreamer1.0-plugins-good:amd64                 1.8.3-1ubuntu0.4   amd64    GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:amd64                 1.8.3-1ubuntu0.1   amd64    GStreamer plugins from the "ugly" set
ii  gstreamer1.0-plugins-ugly-amr:amd64             1.8.3-1ubuntu0.1   amd64    GStreamer plugins from the "ugly" set
ii  gstreamer1.0-pulseaudio:amd64		    1.8.3-1ubuntu0.4   amd64    GStreamer plugin for PulseAudio
ii  gstreamer1.0-tools          		    1.8.3-1~ubuntu0.1  amd64    Tools for use with GStreamer
ii  gstreamer1.0-x:amd64        		    1.8.3-1ubuntu0.2   amd64    GStreamer plugins for X11 and Pango
ii  libgstreamer1.0-0:amd64     		    1.8.3-1~ubuntu0.1  amd64    Core GStreamer libraries and elements
```

**Comment by genodeftest** [comment]
You might be missing the development files (headers).

**Comment by globeone** [comment]
LOL dependancy hell. Snap or Flatpack anyone? 

So to get it to compile on Ubuntu 16.04 you need the following packages

`sudo apt install -t xenial-backports meson`
 `sudo apt install gstreamer1*:amd64`
`sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev fftw3 libfftw3-dev`

Maybe something for the user Install Instructions?

And thanks everyone for all your help! I do appreciate it.

**Comment by globeone** [comment]
I put in my proposal to change the Readme.md. My moodbar works now. Thanks a million!

**Comment by genodeftest** [comment]
> LOL dependancy hell. Snap or Flatpack anyone?

There is no way to compile a package without having headers for the packages it depends on. It does not matter whether you build the package for a distro, Snap or flatpak.

All the dependencies you list here are listed in `README.md` already.
