### ISSUE TITLE
[Regression 1.0 to 1.1] Tests fail on some architectures (ppc64le, aarch64, 390x)

### ISSUE THREAD

**Issue by genodeftest** [exaile/moodbar#8]
Steps to reproduce:
1. Build both moodbar 1.0 and 1.1 for some architectures

What happens:
With moodbar 1.0, the `meson test` is successful for all architectures. With moodbar 1.1, the test fails on ppc64le, aarch64, 390x.

What should happen:
Run tests successfully on all platforms.

Additional information:
Fedora package build
* moodbar 1.1: https://koji.fedoraproject.org/koji/taskinfo?taskID=34490175
* moodbar 1.0: https://koji.fedoraproject.org/koji/taskinfo?taskID=34490248

**Comment by sjohannes** [comment]
Background: The test (there's only one and it didn't exist in v1.0) creates an audio file that plays three tones in sequence which should show up as red, green, and blue on the moodbar.

For whatever reason, on these failing arches the test moodbar ends with the colour (0, 0, 233.6626506). On other arches they are closer to pure blue (0, 0, 255). I don't know what causes the difference, but it's still close enough that I'm not too worried.

I'll just change the [colour difference threshold](https://github.com/exaile/moodbar/blob/3687382ce2070554e0ffe0476c7a8246a99b25e1/test.py#L79) so the test succeeds.

**Comment by genodeftest** [comment]
Thank you very much! As this is not affecting the code itself but only the tests, I guess you won't release a new version any time soon. Am I right? I'd like to know because I want to update the Fedora package and I would wait for the new version tag if you'd release a new version soon. Otherwise, I'd just add your latest commit as a manual patch.

**Comment by sjohannes** [comment]
I don't mind releasing 1.1.1 with just this, since it helps package maintainers. Is there a convenient way to test it first, though? I think QEMU can emulate those architectures but I have no experience with it.

**Comment by genodeftest** [comment]
I'll try doing a build with Fedora's infrastructure and will report back once it is finished.

**Comment by genodeftest** [comment]
Fedora's build was successful, including on the secondary architectures: https://koji.fedoraproject.org/koji/taskinfo?taskID=34512181

Here is the code to trigger this build: https://src.fedoraproject.org/rpms/moodbar/pull-request/3
